<?php

namespace Database\Seeders\CarModels;

use Illuminate\Support\Facades\DB;

Class CarModelsFrom_1_to_25
{
    public static function seed()
    {
      
        DB::table('car_models')->insert([
            ['car_make_id' => 1, 'title' => 'ACE'],
            ['car_make_id' => 1, 'title' => 'Aceca'],
            ['car_make_id' => 1, 'title' => 'Cobra'],
            ['car_make_id' => 2, 'title' => 'CL'],
            ['car_make_id' => 2, 'title' => 'CSX'],
            ['car_make_id' => 2, 'title' => 'EL'],
            ['car_make_id' => 2, 'title' => 'ILX'],
            ['car_make_id' => 2, 'title' => 'Integra'],
            ['car_make_id' => 2, 'title' => 'MDX'],
            ['car_make_id' => 2, 'title' => 'NSX'],
            ['car_make_id' => 2, 'title' => 'RDX'],
            ['car_make_id' => 2, 'title' => 'RL'],
            ['car_make_id' => 2, 'title' => 'RLX'],
            ['car_make_id' => 2, 'title' => 'RSX'],
            ['car_make_id' => 2, 'title' => 'SLX'],
            ['car_make_id' => 2, 'title' => 'TL'],
            ['car_make_id' => 2, 'title' => 'TLX'],
            ['car_make_id' => 2, 'title' => 'TSX'],
            ['car_make_id' => 2, 'title' => 'ZDX'],
            ['car_make_id' => 3, 'title' => 'Diplomat'],
            ['car_make_id' => 3, 'title' => 'Trumpf Junior'],
            ['car_make_id' => 4, 'title' => '105/115'],
            ['car_make_id' => 4, 'title' => '145'],
            ['car_make_id' => 4, 'title' => '146'],
            ['car_make_id' => 4, 'title' => '147'],
            ['car_make_id' => 4, 'title' => '155'],
            ['car_make_id' => 4, 'title' => '156'],
            ['car_make_id' => 4, 'title' => '159'],
            ['car_make_id' => 4, 'title' => '164'],
            ['car_make_id' => 4, 'title' => '166'],
            ['car_make_id' => 4, 'title' => '33'],
            ['car_make_id' => 4, 'title' => '4C'],
            ['car_make_id' => 4, 'title' => '6'],
            ['car_make_id' => 4, 'title' => '75'],
            ['car_make_id' => 4, 'title' => '8C Competizione'],
            ['car_make_id' => 4, 'title' => 'Brera'],
            ['car_make_id' => 4, 'title' => 'Giulia'],
            ['car_make_id' => 4, 'title' => 'Giulietta'],
            ['car_make_id' => 4, 'title' => 'GT'],
            ['car_make_id' => 4, 'title' => 'GTV'],
            ['car_make_id' => 4, 'title' => 'Mito'],
            ['car_make_id' => 4, 'title' => 'Montreal'],
            ['car_make_id' => 4, 'title' => 'S.Z./R.Z.'],
            ['car_make_id' => 4, 'title' => 'Spider'],
            ['car_make_id' => 4, 'title' => 'Stelvio'],
            ['car_make_id' => 5, 'title' => 'B10'],
            ['car_make_id' => 5, 'title' => 'B3'],
            ['car_make_id' => 5, 'title' => 'B4'],
            ['car_make_id' => 5, 'title' => 'B5'],
            ['car_make_id' => 5, 'title' => 'B6'],
            ['car_make_id' => 5, 'title' => 'B7'],]
        );
        DB::table('car_models')->insert([
            ['car_make_id' => 5, 'title' => 'B8'],
            ['car_make_id' => 5, 'title' => 'B3'],
            ['car_make_id' => 5, 'title' => 'D10'],
            ['car_make_id' => 5, 'title' => 'D3'],
            ['car_make_id' => 5, 'title' => 'D4'],
            ['car_make_id' => 5, 'title' => 'D5'],
            ['car_make_id' => 5, 'title' => 'Roadster'],
            ['car_make_id' => 5, 'title' => 'XD3'],
            ['car_make_id' => 6, 'title' => 'A110'],
            ['car_make_id' => 6, 'title' => 'A310'],
            ['car_make_id' => 6, 'title' => 'A610'],
            ['car_make_id' => 6, 'title' => 'GTA'],
            ['car_make_id' => 7, 'title' => 'Eagle'],
            ['car_make_id' => 7, 'title' => 'Hornet'],
            ['car_make_id' => 8, 'title' => '21541 Stalker'],
            ['car_make_id' => 9, 'title' => '10'],
            ['car_make_id' => 9, 'title' => '24'],
            ['car_make_id' => 9, 'title' => 'Spartana'],
            ['car_make_id' => 10, 'title' => 'Rocstar'],
            ['car_make_id' => 10, 'title' => 'Topic'],

            ['car_make_id' => 11, 'title' => 'Cygnet'],
            ['car_make_id' => 11, 'title' => 'DB AR1'],
            ['car_make_id' => 11, 'title' => 'DB11'],
            ['car_make_id' => 11, 'title' => 'DB7'],
            ['car_make_id' => 11, 'title' => 'DB11'],
            ['car_make_id' => 11, 'title' => 'DB9'],
            ['car_make_id' => 11, 'title' => 'DBS'],
            ['car_make_id' => 11, 'title' => 'DBX'],
            ['car_make_id' => 11, 'title' => 'Lagonda'],
            ['car_make_id' => 11, 'title' => 'Rapide'],
            ['car_make_id' => 11, 'title' => 'V8 Vantage'],
            ['car_make_id' => 11, 'title' => 'V8 Zagato'],
            ['car_make_id' => 11, 'title' => 'Vanquish'],
            ['car_make_id' => 11, 'title' => 'Vantage'],
            ['car_make_id' => 12, 'title' => '100'],
            ['car_make_id' => 12, 'title' => '200'],
            ['car_make_id' => 12, 'title' => '50'],
            ['car_make_id' => 12, 'title' => '80'],
            ['car_make_id' => 12, 'title' => '90'],
            ['car_make_id' => 12, 'title' => 'A1'],
            ['car_make_id' => 12, 'title' => 'A2'],
            ['car_make_id' => 12, 'title' => 'A3'],
            ['car_make_id' => 12, 'title' => 'A4'],
            ['car_make_id' => 12, 'title' => 'A4 Allroad'],
            ['car_make_id' => 12, 'title' => 'A5'],
            ['car_make_id' => 12, 'title' => 'A5 Sportback'],
            ['car_make_id' => 12, 'title' => 'A6'],
            ['car_make_id' => 12, 'title' => 'A6 Allroad'],
            ['car_make_id' => 12, 'title' => 'A7'],
            ['car_make_id' => 12, 'title' => 'A8'],]
        );
        DB::table('car_models')->insert([
            ['car_make_id' => 12, 'title' => 'Allroad'],
            ['car_make_id' => 12, 'title' => 'Cabriolet'],
            ['car_make_id' => 12, 'title' => 'Coupe'],
            ['car_make_id' => 12, 'title' => 'e-tron'],
            ['car_make_id' => 12, 'title' => 'NSU RO 80'],
            ['car_make_id' => 12, 'title' => 'Q2'],
            ['car_make_id' => 12, 'title' => 'Q3'],
            ['car_make_id' => 12, 'title' => 'Q3 Sportback'],
            ['car_make_id' => 12, 'title' => 'Q5'],
            ['car_make_id' => 12, 'title' => 'Q7'],
            ['car_make_id' => 12, 'title' => 'Q8'],
            ['car_make_id' => 12, 'title' => 'Quattro'],
            ['car_make_id' => 12, 'title' => 'R8'],
            ['car_make_id' => 12, 'title' => 'R8 LMP'],
            ['car_make_id' => 12, 'title' => 'RS 2'],
            ['car_make_id' => 12, 'title' => 'RS 3'],
            ['car_make_id' => 12, 'title' => 'RS 4'],
            ['car_make_id' => 12, 'title' => 'RS 5'],
            ['car_make_id' => 12, 'title' => 'RS 6'],
            ['car_make_id' => 12, 'title' => 'RS Q3'],
            ['car_make_id' => 12, 'title' => 'RS Q3 Sportback'],
            ['car_make_id' => 12, 'title' => 'S1'],
            ['car_make_id' => 12, 'title' => 'S2'],
            ['car_make_id' => 12, 'title' => 'S3'],
            ['car_make_id' => 12, 'title' => 'S4'],
            ['car_make_id' => 12, 'title' => 'S5'],
            ['car_make_id' => 12, 'title' => 'S6'],
            ['car_make_id' => 12, 'title' => 'S7'],
            ['car_make_id' => 12, 'title' => 'S8'],
            ['car_make_id' => 12, 'title' => 'SQ2'],
            ['car_make_id' => 12, 'title' => 'SQ5'],
            ['car_make_id' => 12, 'title' => 'SQ7'],
            ['car_make_id' => 12, 'title' => 'SQ8'],
            ['car_make_id' => 12, 'title' => 'TT'],
            ['car_make_id' => 12, 'title' => 'TT RS'],
            ['car_make_id' => 12, 'title' => 'TTS'],
            ['car_make_id' => 12, 'title' => 'V8'],
            ['car_make_id' => 12, 'title' => 'TT'],
            ['car_make_id' => 13, 'title' => 'Senat'],
            ['car_make_id' => 14, 'title' => 'FL2'],
            ['car_make_id' => 14, 'title' => 'Metro'],
            ['car_make_id' => 14, 'title' => 'Montego'],
            ['car_make_id' => 14, 'title' => 'Sprite'],
            ['car_make_id' => 15, 'title' => '100'],
            ['car_make_id' => 15, 'title' => '3000'],
            ['car_make_id' => 16, 'title' => 'A 112'],
            ['car_make_id' => 17, 'title' => '2160'],
            ['car_make_id' => 17, 'title' => '2163'],
            ['car_make_id' => 17, 'title' => '3101'],
            ['car_make_id' => 18, 'title' => 'Jeep Cherokee 2500'],
            ['car_make_id' => 18, 'title' => 'Luba (XB624)'],]
        );
        DB::table('car_models')->insert([
            ['car_make_id' => 18, 'title' => 'A1'],
            ['car_make_id' => 18, 'title' => 'Beijing BJ80'],
            ['car_make_id' => 18, 'title' => 'BJ2020'],
            ['car_make_id' => 18, 'title' => 'BJ2026'],
            ['car_make_id' => 18, 'title' => 'BJ212'],
            ['car_make_id' => 18, 'title' => 'EU260'],
            ['car_make_id' => 18, 'title' => 'Huansu H2'],
            ['car_make_id' => 18, 'title' => 'Jeep Cherokee 2500'],
            ['car_make_id' => 18, 'title' => 'Luba (XB624)'],
            ['car_make_id' => 18, 'title' => 'Senova'],
            ['car_make_id' => 19, 'title' => 'Qute'],
            ['car_make_id' => 20, 'title' => 'BD-1322'],
            ['car_make_id' => 21, 'title' => '1989'],
            ['car_make_id' => 21, 'title' => '2018'],
            ['car_make_id' => 22, 'title' => 'BJ 2020'],
            ['car_make_id' => 23, 'title' => 'Arnage'],
            ['car_make_id' => 23, 'title' => 'Azure'],
            ['car_make_id' => 23, 'title' => 'Bentayga'],
            ['car_make_id' => 23, 'title' => 'Brooklands'],
            ['car_make_id' => 23, 'title' => 'Continental'],
            ['car_make_id' => 23, 'title' => 'Continental Flying Spur'],
            ['car_make_id' => 23, 'title' => 'Continental GT'],
            ['car_make_id' => 23, 'title' => 'Eight'],
            ['car_make_id' => 23, 'title' => 'Flying Spur'],
            ['car_make_id' => 23, 'title' => 'Mark VI'],
            ['car_make_id' => 23, 'title' => 'Mulsane'],
            ['car_make_id' => 23, 'title' => 'R Type'],
            ['car_make_id' => 23, 'title' => 'S'],
            ['car_make_id' => 23, 'title' => 'T-Series'],
            ['car_make_id' => 23, 'title' => 'Turbo-R'],
            ['car_make_id' => 24, 'title' => 'Freeclimber'],
            ['car_make_id' => 25, 'title' => 'Vintage'],]
        );
    }
}
