<?php

namespace Database\Seeders\CarModels;

use Illuminate\Support\Facades\DB;

Class CarModelsFrom_101_to_125
{
    public static function seed()
    {
        DB::table('car_models')->insert(
            [
                ['car_make_id' => 101, 'title' => '288 GTO'],
                ['car_make_id' => 101, 'title' => '308'],
                ['car_make_id' => 101, 'title' => '348'],
                ['car_make_id' => 101, 'title' => '360'],
                ['car_make_id' => 101, 'title' => '400'],
                ['car_make_id' => 101, 'title' => '412'],
                ['car_make_id' => 101, 'title' => '456'],
                ['car_make_id' => 101, 'title' => '458'],
                ['car_make_id' => 101, 'title' => '488'],
                ['car_make_id' => 101, 'title' => '512 BB'],
                ['car_make_id' => 101, 'title' => '512 M'],
                ['car_make_id' => 101, 'title' => '512 TR'],
                ['car_make_id' => 101, 'title' => '550'],
                ['car_make_id' => 101, 'title' => '575'],
                ['car_make_id' => 101, 'title' => '575 M'],
                ['car_make_id' => 101, 'title' => '599'],
                ['car_make_id' => 101, 'title' => '612'],
                ['car_make_id' => 101, 'title' => '612 Scaglietti'],
                ['car_make_id' => 101, 'title' => '812'],
                ['car_make_id' => 101, 'title' => '812 Superfast'],
                ['car_make_id' => 101, 'title' => 'California'],
                ['car_make_id' => 101, 'title' => 'Dino 206 GT'],
                ['car_make_id' => 101, 'title' => 'Dino 208/308 GT4'],
                ['car_make_id' => 101, 'title' => 'Dino 246 GT'],
                ['car_make_id' => 101, 'title' => 'Enzo'],
                ['car_make_id' => 101, 'title' => 'F12 Berlinetta'],
                ['car_make_id' => 101, 'title' => 'F355'],
                ['car_make_id' => 101, 'title' => 'F40'],
                ['car_make_id' => 101, 'title' => 'F430'],
                ['car_make_id' => 101, 'title' => 'F50'],
                ['car_make_id' => 101, 'title' => 'F8 Tributo'],
                ['car_make_id' => 101, 'title' => 'FF'],
                ['car_make_id' => 101, 'title' => 'FXX K'],
                ['car_make_id' => 101, 'title' => 'GTC 4 Lusso'],
                ['car_make_id' => 101, 'title' => 'laFerrari'],
                ['car_make_id' => 101, 'title' => 'Mondial'],
                ['car_make_id' => 101, 'title' => 'Monza SP'],
                ['car_make_id' => 101, 'title' => 'Portofino'],
                ['car_make_id' => 101, 'title' => 'Roma'],
                ['car_make_id' => 101, 'title' => 'SF90 Stradale'],
                ['car_make_id' => 101, 'title' => 'Testarossa'],
                ['car_make_id' => 102, 'title' => '124 Spider'],
                ['car_make_id' => 102, 'title' => '124 Sport Spider'],
                ['car_make_id' => 102, 'title' => '125'],
                ['car_make_id' => 102, 'title' => '126'],
                ['car_make_id' => 102, 'title' => '500'],
                ['car_make_id' => 102, 'title' => '500L'],
                ['car_make_id' => 102, 'title' => '500X'],
                ['car_make_id' => 102, 'title' => '508'],
                ['car_make_id' => 102, 'title' => '600'],
                ['car_make_id' => 102, 'title' => '900T'],
                ['car_make_id' => 102, 'title' => 'Albea'],
                ['car_make_id' => 102, 'title' => 'Argenta'],
                ['car_make_id' => 102, 'title' => 'Barchetta'],
                ['car_make_id' => 102, 'title' => 'Brava'],
                ['car_make_id' => 102, 'title' => 'Bravo'],
                ['car_make_id' => 102, 'title' => 'Cinquecento'],
                ['car_make_id' => 102, 'title' => 'Coupe'],
                ['car_make_id' => 102, 'title' => 'Croma'],
                ['car_make_id' => 102, 'title' => 'Doblo'],
                ['car_make_id' => 102, 'title' => 'Fiorino'],
                ['car_make_id' => 102, 'title' => 'Freemont'],
                ['car_make_id' => 102, 'title' => 'Fullback'],
                ['car_make_id' => 102, 'title' => 'Grande Puto'],
                ['car_make_id' => 102, 'title' => 'Idea'],
                ['car_make_id' => 102, 'title' => 'Linea'],
                ['car_make_id' => 102, 'title' => 'Marea'],
                ['car_make_id' => 102, 'title' => 'Multipa'],
                ['car_make_id' => 102, 'title' => 'Palio'],
                ['car_make_id' => 102, 'title' => 'Punto'],
                ['car_make_id' => 102, 'title' => 'Qubo'],
                ['car_make_id' => 102, 'title' => 'Regata'],
                ['car_make_id' => 102, 'title' => 'Ritmo'],
                ['car_make_id' => 102, 'title' => 'Scudo'],
                ['car_make_id' => 102, 'title' => 'Sedici'],
                ['car_make_id' => 102, 'title' => 'Seicento'],
                ['car_make_id' => 102, 'title' => 'Siena'],
                ['car_make_id' => 102, 'title' => 'Stilo'],
                ['car_make_id' => 102, 'title' => 'Strada'],
                ['car_make_id' => 102, 'title' => 'Tempra'],
                ['car_make_id' => 102, 'title' => 'Tipo'],
                ['car_make_id' => 102, 'title' => 'Ulysse'],
                ['car_make_id' => 102, 'title' => 'Uno'],
                ['car_make_id' => 102, 'title' => 'X 1/9'],


            ]
        );
    }
}