<?php

namespace Database\Seeders\CarModels;

use Illuminate\Support\Facades\DB;

Class CarModelsFrom_26_to_50
{
    public static function seed()
    {
        DB::table('car_models')->insert(
[
            ['car_make_id' => 26, 'title' => 'CD'],
            ['car_make_id' => 26, 'title' => 'Type 3'],
            ['car_make_id' => 27, 'title' => '02 (E10)'],
            ['car_make_id' => 27, 'title' => '1 Series'],
            ['car_make_id' => 27, 'title' => '1M'],
            ['car_make_id' => 27, 'title' => '2 Series'],
            ['car_make_id' => 27, 'title' => '2 Series Active Tourer'],
            ['car_make_id' => 27, 'title' => '2 Series Grand Tourer'],
            ['car_make_id' => 27, 'title' => '3 Series'],
            ['car_make_id' => 27, 'title' => '321'],
            ['car_make_id' => 27, 'title' => '326'],
            ['car_make_id' => 27, 'title' => '327'],
            ['car_make_id' => 27, 'title' => '340'],
            ['car_make_id' => 27, 'title' => '4 Series'],
            ['car_make_id' => 27, 'title' => '5 Series'],
            ['car_make_id' => 27, 'title' => '6 Series'],
            ['car_make_id' => 27, 'title' => '7 Series'],
            ['car_make_id' => 27, 'title' => '8 Series'],
            ['car_make_id' => 27, 'title' => 'i3'],
            ['car_make_id' => 27, 'title' => 'i8'],
]        );
        DB::table('car_models')->insert(
[            ['car_make_id' => 27, 'title' => 'M1'],
            ['car_make_id' => 27, 'title' => 'M2'],
            ['car_make_id' => 27, 'title' => 'M3'],
            ['car_make_id' => 27, 'title' => 'M4'],
            ['car_make_id' => 27, 'title' => 'M5'],
            ['car_make_id' => 27, 'title' => 'M6'],
            ['car_make_id' => 27, 'title' => 'M8'],
            ['car_make_id' => 27, 'title' => 'X1'],
            ['car_make_id' => 27, 'title' => 'X2'],
            ['car_make_id' => 27, 'title' => 'X3'],
            ['car_make_id' => 27, 'title' => 'X4'],
            ['car_make_id' => 27, 'title' => 'X5'],
            ['car_make_id' => 27, 'title' => 'X5 M'],
            ['car_make_id' => 27, 'title' => 'X6'],
            ['car_make_id' => 27, 'title' => 'X6 M'],
            ['car_make_id' => 27, 'title' => 'X7'],
            ['car_make_id' => 27, 'title' => 'Z1'],
            ['car_make_id' => 27, 'title' => 'Z3'],
            ['car_make_id' => 27, 'title' => 'Z3 M'],
            ['car_make_id' => 27, 'title' => 'Z4'],
            ['car_make_id' => 27, 'title' => 'Z4 M'],
            ['car_make_id' => 27, 'title' => 'Z8'],
            ['car_make_id' => 28, 'title' => 'BX5'],
            ['car_make_id' => 28, 'title' => 'BX7'],
            ['car_make_id' => 28, 'title' => 'Hansa 1100'],
            ['car_make_id' => 29, 'title' => 'ML 63 Biturbo'],
            ['car_make_id' => 30, 'title' => 'BS2'],
            ['car_make_id' => 30, 'title' => 'BS4'],
            ['car_make_id' => 30, 'title' => 'BS6'],
            ['car_make_id' => 30, 'title' => 'FRV (BS2)'],
            ['car_make_id' => 30, 'title' => 'H230'],
            ['car_make_id' => 30, 'title' => 'H530'],
            ['car_make_id' => 30, 'title' => 'M1'],
            ['car_make_id' => 30, 'title' => 'M1 (BS6)'],
            ['car_make_id' => 30, 'title' => 'M2'],
            ['car_make_id' => 30, 'title' => 'M2 (BS4)'],
            ['car_make_id' => 30, 'title' => 'M3'],
            ['car_make_id' => 30, 'title' => 'M3 (BC3)'],
            ['car_make_id' => 30, 'title' => 'V3'],
            ['car_make_id' => 30, 'title' => 'V5'],
            ['car_make_id' => 31, 'title' => 'Blenheim'],
            ['car_make_id' => 31, 'title' => 'Fighter'],
            ['car_make_id' => 31, 'title' => 'Speedster'],
            ['car_make_id' => 31, 'title' => 'Blenheim Speedster'],
            ['car_make_id' => 32, 'title' => 'Geneva'],
            ['car_make_id' => 32, 'title' => 'la Joya'],
            ['car_make_id' => 33, 'title' => 'Chiron'],
            ['car_make_id' => 33, 'title' => 'EB 110'],
            ['car_make_id' => 33, 'title' => 'EB 112'],
            ['car_make_id' => 33, 'title' => 'EB Veyron 16.4'],
            ['car_make_id' => 33, 'title' => 'Type 55'],
            ['car_make_id' => 33, 'title' => 'Veyron'],
            ['car_make_id' => 34, 'title' => 'Cascada'],
            ['car_make_id' => 34, 'title' => 'Century'],
]        );
        DB::table('car_models')->insert(
[            ['car_make_id' => 34, 'title' => 'Electra'],
            ['car_make_id' => 34, 'title' => 'Enclave'],
            ['car_make_id' => 34, 'title' => 'Encore'],
            ['car_make_id' => 34, 'title' => 'Envision'],
            ['car_make_id' => 34, 'title' => 'Estate Wagon'],
            ['car_make_id' => 34, 'title' => 'Excelle'],
            ['car_make_id' => 34, 'title' => 'GL8'],
            ['car_make_id' => 34, 'title' => 'GS'],
            ['car_make_id' => 34, 'title' => 'LaCrosse'],
            ['car_make_id' => 34, 'title' => 'LeSabre'],
            ['car_make_id' => 34, 'title' => 'Limited'],
            ['car_make_id' => 34, 'title' => 'Lucerne'],
            ['car_make_id' => 34, 'title' => 'Park Avenue'],
            ['car_make_id' => 34, 'title' => 'Century'],
            ['car_make_id' => 34, 'title' => 'Rainer'],
            ['car_make_id' => 34, 'title' => 'Reatta'],
            ['car_make_id' => 34, 'title' => 'Regal'],
            ['car_make_id' => 34, 'title' => 'Rendezvous'],
            ['car_make_id' => 34, 'title' => 'Riviera'],
            ['car_make_id' => 34, 'title' => 'Roadmaster'],
            ['car_make_id' => 34, 'title' => 'Skyhawk'],
            ['car_make_id' => 34, 'title' => 'Skylark'],
            ['car_make_id' => 34, 'title' => 'Special'],
            ['car_make_id' => 34, 'title' => 'Super'],
            ['car_make_id' => 34, 'title' => 'Terraza'],
            ['car_make_id' => 34, 'title' => 'Verano'],
            ['car_make_id' => 34, 'title' => 'Wildcat'],
            ['car_make_id' => 35, 'title' => 'F0'],
            ['car_make_id' => 35, 'title' => 'F3'],
            ['car_make_id' => 35, 'title' => 'F3-R'],
            ['car_make_id' => 35, 'title' => 'F5'],
            ['car_make_id' => 35, 'title' => 'F6'],
            ['car_make_id' => 35, 'title' => 'F8 (S8)'],
            ['car_make_id' => 35, 'title' => 'Flyer'],
            ['car_make_id' => 35, 'title' => 'G3'],
            ['car_make_id' => 35, 'title' => 'G6'],
            ['car_make_id' => 35, 'title' => 'L3'],
            ['car_make_id' => 35, 'title' => 'M6'],
            ['car_make_id' => 35, 'title' => 'S6'],
            ['car_make_id' => 36, 'title' => 'Allante'],
            ['car_make_id' => 36, 'title' => 'ATS'],
            ['car_make_id' => 36, 'title' => 'ATS-V'],
            ['car_make_id' => 36, 'title' => 'BLS'],
            ['car_make_id' => 36, 'title' => 'Brougham'],
            ['car_make_id' => 36, 'title' => 'Catera'],
            ['car_make_id' => 36, 'title' => 'CT4'],
            ['car_make_id' => 36, 'title' => 'CT4-V'],
            ['car_make_id' => 36, 'title' => 'CT5'],
            ['car_make_id' => 36, 'title' => 'CT5-V'],
            ['car_make_id' => 36, 'title' => 'CT6'],
            ['car_make_id' => 36, 'title' => 'CTS'],
            ['car_make_id' => 36, 'title' => 'CTS-V'],
            ['car_make_id' => 36, 'title' => 'DeVille'],
            ['car_make_id' => 36, 'title' => 'DTS'],
            ['car_make_id' => 36, 'title' => 'Eldorado'],
            ['car_make_id' => 36, 'title' => 'ELR'],
            ['car_make_id' => 36, 'title' => 'Escalade'],
            ['car_make_id' => 36, 'title' => 'Fleetwood'],
            ['car_make_id' => 36, 'title' => 'LSE'],
            ['car_make_id' => 36, 'title' => 'Series 62'],
            ['car_make_id' => 36, 'title' => 'SeVille'],
            ['car_make_id' => 36, 'title' => 'Sixty Special'],
            ['car_make_id' => 36, 'title' => 'SRX'],
            ['car_make_id' => 36, 'title' => 'STS'],
            ['car_make_id' => 36, 'title' => 'XLR'],
            ['car_make_id' => 36, 'title' => 'XT4'],
            ['car_make_id' => 36, 'title' => 'XT5'],
            ['car_make_id' => 36, 'title' => 'XT6'],
            ['car_make_id' => 36, 'title' => 'XTS'],
            ['car_make_id' => 37, 'title' => 'C12'],
            ['car_make_id' => 38, 'title' => 'FX4'],
            ['car_make_id' => 38, 'title' => 'FX4S'],
            ['car_make_id' => 39, 'title' => '21'],
            ['car_make_id' => 39, 'title' => 'CSR'],
]        );
        DB::table('car_models')->insert(
          [  ['car_make_id' => 39, 'title' => 'Seven'],
            ['car_make_id' => 40, 'title' => 'Benni'],
            ['car_make_id' => 41, 'title' => 'Alsvin V7'],
            ['car_make_id' => 41, 'title' => 'BenBen Mini'],
            ['car_make_id' => 41, 'title' => 'Benni'],
            ['car_make_id' => 41, 'title' => 'CM-8'],
            ['car_make_id' => 41, 'title' => 'CS35'],
            ['car_make_id' => 41, 'title' => 'CS35 Plus'],
            ['car_make_id' => 41, 'title' => 'CS55'],
            ['car_make_id' => 41, 'title' => 'CS75'],
            ['car_make_id' => 41, 'title' => 'CX20'],
            ['car_make_id' => 41, 'title' => 'Eado'],
            ['car_make_id' => 41, 'title' => 'Raeton'],
            ['car_make_id' => 41, 'title' => 'Z-Shine'],
            ['car_make_id' => 42, 'title' => 'Flying'],
            ['car_make_id' => 42, 'title' => 'SUV (CS6)'],
            ['car_make_id' => 43, 'title' => 'Ideal'],
            ['car_make_id' => 44, 'title' => 'Amulet'],
            ['car_make_id' => 44, 'title' => 'Arrizo 3'],
            ['car_make_id' => 44, 'title' => 'Arrizo 7'],
            ['car_make_id' => 44, 'title' => 'B13'],
            ['car_make_id' => 44, 'title' => 'Bonus'],
            ['car_make_id' => 44, 'title' => 'CrossEastar'],
            ['car_make_id' => 44, 'title' => 'E5'],
            ['car_make_id' => 44, 'title' => 'Eastar'],
            ['car_make_id' => 44, 'title' => 'Fora'],
            ['car_make_id' => 44, 'title' => 'IndiS'],
            ['car_make_id' => 44, 'title' => 'Karry'],
            ['car_make_id' => 44, 'title' => 'Kimo'],
            ['car_make_id' => 44, 'title' => 'M11'],
            ['car_make_id' => 44, 'title' => 'Oriental Sun'],
            ['car_make_id' => 44, 'title' => 'QQ'],
            ['car_make_id' => 44, 'title' => 'QQ6'],
            ['car_make_id' => 44, 'title' => 'QQme'],
            ['car_make_id' => 44, 'title' => 'Sweet (QQ)'],
            ['car_make_id' => 44, 'title' => 'Tiggo'],
            ['car_make_id' => 44, 'title' => 'Tiggo 2'],
            ['car_make_id' => 44, 'title' => 'Tiggo 3'],
            ['car_make_id' => 44, 'title' => 'Tiggo 4'],
            ['car_make_id' => 44, 'title' => 'Tiggo 5'],
            ['car_make_id' => 44, 'title' => 'Tiggo 7'],
            ['car_make_id' => 44, 'title' => 'Tiggo 7 pro'],
            ['car_make_id' => 44, 'title' => 'Tiggo 8'],
            ['car_make_id' => 44, 'title' => 'Very'],
            ['car_make_id' => 44, 'title' => 'Windcloud'],
            ['car_make_id' => 45, 'title' => 'TXL'],
            ['car_make_id' => 46, 'title' => 'Agile'],
            ['car_make_id' => 46, 'title' => 'Alero'],
            ['car_make_id' => 46, 'title' => 'Apache'],
            ['car_make_id' => 46, 'title' => 'Astra'],
        ]);
        DB::table('car_models')->insert(
        [    ['car_make_id' => 46, 'title' => 'Avalanche'],
            ['car_make_id' => 46, 'title' => 'Aveo'],
            ['car_make_id' => 46, 'title' => 'Beat'],
            ['car_make_id' => 46, 'title' => 'Beretta'],
            ['car_make_id' => 46, 'title' => 'Blazer'],
            ['car_make_id' => 46, 'title' => 'C/K'],
            ['car_make_id' => 46, 'title' => 'Camaro'],
            ['car_make_id' => 46, 'title' => 'Caprice'],
            ['car_make_id' => 46, 'title' => 'Captiva'],
            ['car_make_id' => 46, 'title' => 'Cavalier'],
            ['car_make_id' => 46, 'title' => 'Celebrity'],
            ['car_make_id' => 46, 'title' => 'Celta'],
            ['car_make_id' => 46, 'title' => 'Chevelle'],
            ['car_make_id' => 46, 'title' => 'Citation'],
            ['car_make_id' => 46, 'title' => 'Cobalt'],
            ['car_make_id' => 46, 'title' => 'Colorado'],
            ['car_make_id' => 46, 'title' => 'Corsa'],
            ['car_make_id' => 46, 'title' => 'Corsica'],
            ['car_make_id' => 46, 'title' => 'Corviar'],
            ['car_make_id' => 46, 'title' => 'Corvette'],
            ['car_make_id' => 46, 'title' => 'Cruze'],
            ['car_make_id' => 46, 'title' => 'CSV CR8'],
            ['car_make_id' => 46, 'title' => 'D20'],
            ['car_make_id' => 46, 'title' => 'Deluxe'],
            ['car_make_id' => 46, 'title' => 'El Camino'],
            ['car_make_id' => 46, 'title' => 'Enjoy'],
            ['car_make_id' => 46, 'title' => 'Epica'],
            ['car_make_id' => 46, 'title' => 'Equinox'],
            ['car_make_id' => 46, 'title' => 'Evanda'],
            ['car_make_id' => 46, 'title' => 'Express'],
            ['car_make_id' => 46, 'title' => 'Forester'],
            ['car_make_id' => 46, 'title' => 'Grand Vitara'],
            ['car_make_id' => 46, 'title' => 'HHR'],
            ['car_make_id' => 46, 'title' => 'Impala'],
            ['car_make_id' => 46, 'title' => 'Ipanema'],
            ['car_make_id' => 46, 'title' => 'Jimmy'],
            ['car_make_id' => 46, 'title' => 'Kadett'],
            ['car_make_id' => 46, 'title' => 'Kalos'],
            ['car_make_id' => 46, 'title' => 'Kommando'],
            ['car_make_id' => 46, 'title' => 'Lacetti'],
            ['car_make_id' => 46, 'title' => 'Lanos'],
            ['car_make_id' => 46, 'title' => 'Lova'],
            ['car_make_id' => 46, 'title' => 'Lumina'],
            ['car_make_id' => 46, 'title' => 'Lumina APV'],
            ['car_make_id' => 46, 'title' => 'LUV D-MAX'],
            ['car_make_id' => 46, 'title' => 'Malibu'],
            ['car_make_id' => 46, 'title' => 'Master'],
            ['car_make_id' => 46, 'title' => 'Matiz'],
            ['car_make_id' => 46, 'title' => 'Meriva'],
            ['car_make_id' => 46, 'title' => 'Metro'],
            ['car_make_id' => 46, 'title' => 'Montana'],
            ['car_make_id' => 46, 'title' => 'Monte Carlo'],
            ['car_make_id' => 46, 'title' => 'Monza'],
            ['car_make_id' => 46, 'title' => 'MW'],
            ['car_make_id' => 46, 'title' => 'N200'],
            ['car_make_id' => 46, 'title' => 'N300'],
            ['car_make_id' => 46, 'title' => 'Nexia'],
            ['car_make_id' => 46, 'title' => 'Niva'],
            ['car_make_id' => 46, 'title' => 'Nova'],
            ['car_make_id' => 46, 'title' => 'Nubira'],
            ['car_make_id' => 46, 'title' => 'Omega'],
            ['car_make_id' => 46, 'title' => 'Onix'],
            ['car_make_id' => 46, 'title' => 'Optra'],
            ['car_make_id' => 46, 'title' => 'Orlando'],
            ['car_make_id' => 46, 'title' => 'Prisma'],
            ['car_make_id' => 46, 'title' => 'Prizm'],
            ['car_make_id' => 46, 'title' => 'Rezzo'],
            ['car_make_id' => 46, 'title' => 'S-10'],
            ['car_make_id' => 46, 'title' => 'Sail'],
            ['car_make_id' => 46, 'title' => 'Silverado'],
            ['car_make_id' => 46, 'title' => 'Sonic'],
            ['car_make_id' => 46, 'title' => 'Sonora'],
            ['car_make_id' => 46, 'title' => 'Spark'],
            ['car_make_id' => 46, 'title' => 'Spin'],
            ['car_make_id' => 46, 'title' => 'SS'],
            ['car_make_id' => 46, 'title' => 'SSR'],
        ]);
        DB::table('car_models')->insert(
        [    ['car_make_id' => 46, 'title' => 'Starcraft'],
            ['car_make_id' => 46, 'title' => 'Suburban'],
            ['car_make_id' => 46, 'title' => 'Tacuma'],
            ['car_make_id' => 46, 'title' => 'Tahoe'],
            ['car_make_id' => 46, 'title' => 'Tavera'],
            ['car_make_id' => 46, 'title' => 'Tornado'],
            ['car_make_id' => 46, 'title' => 'Tracker'],
            ['car_make_id' => 46, 'title' => 'Trailblazer'],
            ['car_make_id' => 46, 'title' => 'Trans Sport'],
            ['car_make_id' => 46, 'title' => 'Traverse'],
            ['car_make_id' => 46, 'title' => 'Uplander'],
            ['car_make_id' => 46, 'title' => 'Utility'],
            ['car_make_id' => 46, 'title' => 'Van'],
            ['car_make_id' => 46, 'title' => 'Vectra'],
            ['car_make_id' => 46, 'title' => 'Vega'],
            ['car_make_id' => 46, 'title' => 'Venture'],
            ['car_make_id' => 46, 'title' => 'Vitara'],
            ['car_make_id' => 46, 'title' => 'Viva'],
            ['car_make_id' => 46, 'title' => 'Vivant'],
            ['car_make_id' => 46, 'title' => 'Volt'],
            ['car_make_id' => 46, 'title' => 'Zafira'],
            ['car_make_id' => 47, 'title' => '300 Letter Series'],
            ['car_make_id' => 47, 'title' => '300C'],
            ['car_make_id' => 47, 'title' => 'Aspen'],
            ['car_make_id' => 47, 'title' => 'Cirrus'],
            ['car_make_id' => 47, 'title' => 'Concorde'],
            ['car_make_id' => 47, 'title' => 'Cordoba'],
            ['car_make_id' => 47, 'title' => 'Crossfire'],
            ['car_make_id' => 47, 'title' => 'Daytona'],
            ['car_make_id' => 47, 'title' => 'ES'],
            ['car_make_id' => 47, 'title' => 'Fifth Avenue'],
            ['car_make_id' => 47, 'title' => 'Imperial'],
            ['car_make_id' => 47, 'title' => 'Intrepid'],
            ['car_make_id' => 47, 'title' => 'leBaron'],
            ['car_make_id' => 47, 'title' => 'LHS'],
            ['car_make_id' => 47, 'title' => 'Neon'],
            ['car_make_id' => 47, 'title' => 'New Yorker'],
            ['car_make_id' => 47, 'title' => 'New Port'],
            ['car_make_id' => 47, 'title' => 'Pacifica'],
            ['car_make_id' => 47, 'title' => 'Prowler'],
            ['car_make_id' => 47, 'title' => 'PT Cruizer'],
            ['car_make_id' => 47, 'title' => 'Sebring'],
            ['car_make_id' => 47, 'title' => 'TC by Maserati'],
            ['car_make_id' => 47, 'title' => 'Town & Country'],
            ['car_make_id' => 47, 'title' => 'Vision'],
            ['car_make_id' => 47, 'title' => 'Voyager'],
            ['car_make_id' => 48, 'title' => '2 CV'],
            ['car_make_id' => 47, 'title' => 'AX'],
            ['car_make_id' => 47, 'title' => 'Berlingo'],
            ['car_make_id' => 47, 'title' => 'BX'],
            ['car_make_id' => 47, 'title' => 'C-Crosser'],
            ['car_make_id' => 47, 'title' => 'C-Elysee'],
            ['car_make_id' => 47, 'title' => 'C-Triomphe'],
            ['car_make_id' => 47, 'title' => 'C1'],
            ['car_make_id' => 47, 'title' => 'C2'],
            ['car_make_id' => 47, 'title' => 'C3'],
            ['car_make_id' => 47, 'title' => 'C3 AirCross'],
            ['car_make_id' => 47, 'title' => 'C3 Picasso'],
            ['car_make_id' => 47, 'title' => 'C4'],
            ['car_make_id' => 47, 'title' => 'C4 AirCross'],
            ['car_make_id' => 47, 'title' => 'C4 Cactus'],
            ['car_make_id' => 47, 'title' => 'C4 Picasso'],
            ['car_make_id' => 47, 'title' => 'C4 SpaceTourer'],
        ]);
        DB::table('car_models')->insert(
            [   ['car_make_id' => 47, 'title' => 'C4'],
                ['car_make_id' => 47, 'title' => 'C5'],
                ['car_make_id' => 47, 'title' => 'C5 AirCross'],
                ['car_make_id' => 47, 'title' => 'C6'],
                ['car_make_id' => 47, 'title' => 'C8'],
                ['car_make_id' => 47, 'title' => 'CX'],
                ['car_make_id' => 47, 'title' => 'DS'],
                ['car_make_id' => 47, 'title' => 'DS3'],
                ['car_make_id' => 47, 'title' => 'DS4'],
                ['car_make_id' => 47, 'title' => 'Evasion'],
                ['car_make_id' => 47, 'title' => 'Jumpy'],
                ['car_make_id' => 47, 'title' => 'Nemo'],
                ['car_make_id' => 47, 'title' => 'Saxo'],
                ['car_make_id' => 47, 'title' => 'SpaceTourer'],
                ['car_make_id' => 47, 'title' => 'Visa'],
                ['car_make_id' => 47, 'title' => 'Xantia'],
                ['car_make_id' => 47, 'title' => 'XM'],
                ['car_make_id' => 47, 'title' => 'Xsara'],
                ['car_make_id' => 47, 'title' => 'Xsara Picasso'],
                ['car_make_id' => 47, 'title' => 'ZX'],
                ['car_make_id' => 48, 'title' => 'V16T'],
                ['car_make_id' => 49, 'title' => 'T-Rex'],
                ['car_make_id' => 50, 'title' => 'L-29'],
]        );
    }
}
