<?php

namespace Database\Seeders\CarModels;

use Illuminate\Support\Facades\DB;

Class CarModelsFrom_76_to_100
{
    public static function seed()
    {
        DB::table('car_models')->insert(
            [['car_make_id' => 76, 'title' => '250 GTO'],
            ['car_make_id' => 76, 'title' => '288 GTO'],
            ['car_make_id' => 76, 'title' => '308'],
            ['car_make_id' => 76, 'title' => '348'],
            ['car_make_id' => 76, 'title' => '360'],
            ['car_make_id' => 76, 'title' => '400'],
            ['car_make_id' => 76, 'title' => '412'],
            ['car_make_id' => 76, 'title' => '456'],
            ['car_make_id' => 76, 'title' => '458'],
            ['car_make_id' => 76, 'title' => '488'],
            ['car_make_id' => 76, 'title' => '512 BB'],
            ['car_make_id' => 76, 'title' => '512 M'],
            ['car_make_id' => 76, 'title' => '512 TR'],
            ['car_make_id' => 76, 'title' => '550'],
            ['car_make_id' => 76, 'title' => '575'],
            ['car_make_id' => 76, 'title' => '575M'],
            ['car_make_id' => 76, 'title' => '599'],
            ['car_make_id' => 76, 'title' => '612'],
            ['car_make_id' => 76, 'title' => '612 Scaglietti'],
            ['car_make_id' => 76, 'title' => '812'],
            ['car_make_id' => 76, 'title' => '812 Superfast'],
            ['car_make_id' => 76, 'title' => 'California'],
            ['car_make_id' => 76, 'title' => 'Dino 206 GT'],
            ['car_make_id' => 76, 'title' => 'Dino 208/308 GT4'],
            ['car_make_id' => 76, 'title' => 'Dino 246 GT'],
            ['car_make_id' => 76, 'title' => 'Enzo'],
            ['car_make_id' => 76, 'title' => 'F12 Berlinetta'],
            ['car_make_id' => 76, 'title' => 'F355'],
            ['car_make_id' => 76, 'title' => 'F40'],
            ['car_make_id' => 76, 'title' => 'F430'],
            ['car_make_id' => 76, 'title' => 'F50'],
            ['car_make_id' => 76, 'title' => 'F8 Tributo'],
            ['car_make_id' => 76, 'title' => 'FF'],
            ['car_make_id' => 76, 'title' => 'FXX K'],
            ['car_make_id' => 76, 'title' => 'GTC4 Lusso'],
            ['car_make_id' => 76, 'title' => 'LaFerrari'],
            ['car_make_id' => 76, 'title' => 'Mondial'],
            ['car_make_id' => 76, 'title' => 'Monza SP'],
            ['car_make_id' => 76, 'title' => 'Portofino'],
            ['car_make_id' => 76, 'title' => 'Roma'],
            ['car_make_id' => 76, 'title' => 'SF90 Stradale'],
            ['car_make_id' => 76, 'title' => 'Testarossa']]
        );
        DB::table('car_models')->insert(
            [['car_make_id' => 77, 'title' => '124 Spider'],
            ['car_make_id' => 77, 'title' => '124 Sport Spider'],
            ['car_make_id' => 77, 'title' => '125'],
            ['car_make_id' => 77, 'title' => '126'],
            ['car_make_id' => 77, 'title' => '500'],
            ['car_make_id' => 77, 'title' => '500L'],
            ['car_make_id' => 77, 'title' => '500X'],
            ['car_make_id' => 77, 'title' => '508'],
            ['car_make_id' => 77, 'title' => '600'],
            ['car_make_id' => 77, 'title' => '900T'],
            ['car_make_id' => 77, 'title' => 'Albea'],
            ['car_make_id' => 77, 'title' => 'Argenta'],
            ['car_make_id' => 77, 'title' => 'Barchetta'],
            ['car_make_id' => 77, 'title' => 'Bravo'],
            ['car_make_id' => 77, 'title' => 'Cinquecento'],
            ['car_make_id' => 77, 'title' => 'Coupe'],
            ['car_make_id' => 77, 'title' => 'Croma'],
            ['car_make_id' => 77, 'title' => 'Doblo'],
            ['car_make_id' => 77, 'title' => 'Fiorino'],
            ['car_make_id' => 77, 'title' => 'Freemont'],
            ['car_make_id' => 77, 'title' => 'Fullback'],
            ['car_make_id' => 77, 'title' => 'Grand Punto'],
            ['car_make_id' => 77, 'title' => 'Idea'],
            ['car_make_id' => 77, 'title' => 'Linea'],
            ['car_make_id' => 77, 'title' => 'Marea'],
            ['car_make_id' => 77, 'title' => 'Multipa'],
            ['car_make_id' => 77, 'title' => 'Palio'],
            ['car_make_id' => 77, 'title' => 'Panda'],
            ['car_make_id' => 77, 'title' => 'Punto'],
            ['car_make_id' => 77, 'title' => 'Regata'],
            ['car_make_id' => 77, 'title' => 'Ritmo'],
            ['car_make_id' => 77, 'title' => 'Scudo'],
            ['car_make_id' => 77, 'title' => 'Sedici'],
            ['car_make_id' => 77, 'title' => 'Seicento'],
            ['car_make_id' => 77, 'title' => 'Siena'],
            ['car_make_id' => 77, 'title' => 'Stilo'],
            ['car_make_id' => 77, 'title' => 'Strada'],
            ['car_make_id' => 77, 'title' => 'Tempra'],
            ['car_make_id' => 77, 'title' => 'Tipo'],
            ['car_make_id' => 77, 'title' => 'Ulysee'],
            ['car_make_id' => 77, 'title' => 'Uno'],
            ['car_make_id' => 77, 'title' => 'X 1/9'],]
        );
        DB::table('car_models')->insert(
            [['car_make_id' => 78, 'title' => 'Karma'],
            ['car_make_id' => 79, 'title' => 'F'],
            ['car_make_id' => 80, 'title' => 'Aerostar'],
            ['car_make_id' => 80, 'title' => 'Aspire'],
            ['car_make_id' => 80, 'title' => 'Bronco'],
            ['car_make_id' => 80, 'title' => 'Bronco Sport'],
            ['car_make_id' => 80, 'title' => 'Bronco II'],
            ['car_make_id' => 80, 'title' => 'C-Max'],
            ['car_make_id' => 80, 'title' => 'Contour'],
            ['car_make_id' => 80, 'title' => 'Cortina'],
            ['car_make_id' => 80, 'title' => 'Cougar'],
            ['car_make_id' => 80, 'title' => 'Crown Victoria'],
            ['car_make_id' => 80, 'title' => 'Custom'],
            ['car_make_id' => 80, 'title' => 'E-Series'],
            ['car_make_id' => 80, 'title' => 'Econo-line'],
            ['car_make_id' => 80, 'title' => 'EcoSport'],
            ['car_make_id' => 80, 'title' => 'Edge'],
            ['car_make_id' => 80, 'title' => 'Escape'],
            ['car_make_id' => 80, 'title' => 'Escort'],
            ['car_make_id' => 80, 'title' => 'Escort (North America)'],
            ['car_make_id' => 80, 'title' => 'Everest'],
            ['car_make_id' => 80, 'title' => 'Excursion'],
            ['car_make_id' => 80, 'title' => 'Expedition'],
            ['car_make_id' => 80, 'title' => 'Explorer'],
            ['car_make_id' => 80, 'title' => 'Explorer Sport Tac'],
            ['car_make_id' => 80, 'title' => 'F-150'],
            ['car_make_id' => 80, 'title' => 'F-Series'],
            ['car_make_id' => 80, 'title' => 'Fairlane'],
            ['car_make_id' => 80, 'title' => 'Fairmont'],
            ['car_make_id' => 80, 'title' => 'Falcon'],
            ['car_make_id' => 80, 'title' => 'Festiva'],
            ['car_make_id' => 80, 'title' => 'Fiesta'],
            ['car_make_id' => 80, 'title' => 'Fiesta ST'],
            ['car_make_id' => 80, 'title' => 'Five Hundredd'],
            ['car_make_id' => 80, 'title' => 'Flex'],
            ['car_make_id' => 80, 'title' => 'Focus'],
            ['car_make_id' => 80, 'title' => 'Focus (North America)'],
            ['car_make_id' => 80, 'title' => 'Focus ST'],
            ['car_make_id' => 80, 'title' => 'Freda'],
            ['car_make_id' => 80, 'title' => 'Freestyle'],
            ['car_make_id' => 80, 'title' => 'Fusion'],
            ['car_make_id' => 80, 'title' => 'Fusion (North America)'],
            ['car_make_id' => 80, 'title' => 'Galaxy'],
            ['car_make_id' => 80, 'title' => 'Granada (North America)'],
            ['car_make_id' => 80, 'title' => 'GT'],
            ['car_make_id' => 80, 'title' => 'GT40'],
            ['car_make_id' => 80, 'title' => 'Ikon'],
            ['car_make_id' => 80, 'title' => 'Ka'],
            ['car_make_id' => 80, 'title' => 'M151'],
            ['car_make_id' => 80, 'title' => 'Mainline'],
            ['car_make_id' => 80, 'title' => 'Maverick'],
            ['car_make_id' => 80, 'title' => 'Model T'],
            ['car_make_id' => 80, 'title' => 'Mondeo'],
            ['car_make_id' => 80, 'title' => 'Mustang'],
            ['car_make_id' => 80, 'title' => 'Probe'],
            ['car_make_id' => 80, 'title' => 'Puma'],
            ['car_make_id' => 80, 'title' => 'Ranger'],
            ['car_make_id' => 80, 'title' => 'S-Max'],
            ['car_make_id' => 80, 'title' => 'Ranger (North America)'],
            ['car_make_id' => 80, 'title' => 'Scorpio'],
            ['car_make_id' => 80, 'title' => 'Sierra'],
            ['car_make_id' => 80, 'title' => 'Taurus'],
            ['car_make_id' => 80, 'title' => 'Street KA'],
            ['car_make_id' => 80, 'title' => 'Taurus X'],
            ['car_make_id' => 80, 'title' => 'Telstar'],
            ['car_make_id' => 80, 'title' => 'Tempo'],
            ['car_make_id' => 80, 'title' => 'Territory'],
            ['car_make_id' => 80, 'title' => 'Thunderbird'],
            ['car_make_id' => 80, 'title' => 'Torino'],
            ['car_make_id' => 80, 'title' => 'Tourneo'],
            ['car_make_id' => 80, 'title' => 'Tourneo Connect'],
            ['car_make_id' => 80, 'title' => 'Tourneo Custom'],
            ['car_make_id' => 80, 'title' => 'Transit Connect'],
            ['car_make_id' => 80, 'title' => 'Windster'],]
        );
        DB::table('car_models')->insert(
            [['car_make_id' => 81, 'title' => 'Gratour'],
            ['car_make_id' => 81, 'title' => 'Sauvana'],
            ['car_make_id' => 81, 'title' => 'Tunland'],
            ['car_make_id' => 82, 'title' => '125P'],
            ['car_make_id' => 83, 'title' => '6500 Land King'],
            ['car_make_id' => 84, 'title' => 'GN8'],
            ['car_make_id' => 84, 'title' => 'Trumpchi GS8'],
            ['car_make_id' => 85, 'title' => '12 Zim'],
            ['car_make_id' => 85, 'title' => '13 Chaika'],
            ['car_make_id' => 86, 'title' => '14 Chaika'],
            ['car_make_id' => 86, 'title' => '18'],
            ['car_make_id' => 86, 'title' => '21 Volga'],
            ['car_make_id' => 86, 'title' => '22 Volga'],
            ['car_make_id' => 86, 'title' => '2308 Attaman'],
            ['car_make_id' => 86, 'title' => '2330 Tigr'],
            ['car_make_id' => 86, 'title' => '24 Volga'],
            ['car_make_id' => 86, 'title' => '3102 Volga'],
            ['car_make_id' => 86, 'title' => '31029 Volga'],
            ['car_make_id' => 86, 'title' => '3103 Volga'],
            ['car_make_id' => 86, 'title' => '3105 Volga'],
            ['car_make_id' => 86, 'title' => '3110 Volga'],
            ['car_make_id' => 86, 'title' => '3111 Volga'],
            ['car_make_id' => 86, 'title' => '46'],
            ['car_make_id' => 86, 'title' => '61'],
            ['car_make_id' => 86, 'title' => '64'],
            ['car_make_id' => 86, 'title' => '67'],
            ['car_make_id' => 86, 'title' => '69'],
            ['car_make_id' => 86, 'title' => 'A'],
            ['car_make_id' => 86, 'title' => 'M-20 Pobeda'],
            ['car_make_id' => 86, 'title' => 'M-72'],
            ['car_make_id' => 86, 'title' => 'M1'],
            ['car_make_id' => 86, 'title' => 'Siber'],
            ['car_make_id' => 86, 'title' => 'Sobol'],
            ['car_make_id' => 86, 'title' => 'Volga Siber'],
            ['car_make_id' => 87, 'title' => 'Atlas'],
            ['car_make_id' => 87, 'title' => 'Beauty Leopard'],
            ['car_make_id' => 87, 'title' => 'CK Otaka'],
            ['car_make_id' => 87, 'title' => 'Cool Ray'],
            ['car_make_id' => 87, 'title' => 'Emgrand 7'],
            ['car_make_id' => 87, 'title' => 'Emgrand EC7'],
            ['car_make_id' => 87, 'title' => 'Emgrand GT'],
            ['car_make_id' => 87, 'title' => 'Emgrand X7'],
            ['car_make_id' => 87, 'title' => 'MC Vision'],
            ['car_make_id' => 87, 'title' => 'GC 6'],
            ['car_make_id' => 87, 'title' => 'GC 9'],
            ['car_make_id' => 87, 'title' => 'GS'],
            ['car_make_id' => 87, 'title' => 'GX7'],
            ['car_make_id' => 87, 'title' => 'Haoqing'],
            ['car_make_id' => 87, 'title' => 'LC Panda'],
            ['car_make_id' => 87, 'title' => 'MK'],
            ['car_make_id' => 87, 'title' => 'Otaka'],
            ['car_make_id' => 87, 'title' => 'SC7'],
            ['car_make_id' => 87, 'title' => 'Tugella'],
            ['car_make_id' => 87, 'title' => 'TX4'],
            ['car_make_id' => 87, 'title' => 'Vision'],
            ['car_make_id' => 88, 'title' => 'G70'],
            ['car_make_id' => 88, 'title' => 'G80'],
            ['car_make_id' => 88, 'title' => 'G90'],
            ['car_make_id' => 88, 'title' => 'GV70'],
            ['car_make_id' => 88, 'title' => 'GV80'],]
        );
        DB::table('car_models')->insert(
            [['car_make_id' => 89, 'title' => 'Metro'],
            ['car_make_id' => 89, 'title' => 'Prizm'],
            ['car_make_id' => 89, 'title' => 'Spectrum'],
            ['car_make_id' => 89, 'title' => 'Storm'],
            ['car_make_id' => 89, 'title' => 'Tracker'],
            ['car_make_id' => 90, 'title' => '100'],
            ['car_make_id' => 90, 'title' => 'Acadia'],
            ['car_make_id' => 90, 'title' => 'Canyon'],
            ['car_make_id' => 90, 'title' => 'Envoy'],
            ['car_make_id' => 90, 'title' => 'Jimmy'],
            ['car_make_id' => 90, 'title' => 'Safari'],
            ['car_make_id' => 90, 'title' => 'Savanna'],
            ['car_make_id' => 90, 'title' => 'Sierra'],
            ['car_make_id' => 90, 'title' => 'Sonoma'],
            ['car_make_id' => 90, 'title' => 'Suburban'],
            ['car_make_id' => 90, 'title' => 'Syclone'],
            ['car_make_id' => 90, 'title' => 'Terrain'],
            ['car_make_id' => 90, 'title' => 'Typhoon'],
            ['car_make_id' => 90, 'title' => 'Vandura'],
            ['car_make_id' => 90, 'title' => 'Yukon'],
            ['car_make_id' => 91, 'title' => 'Troy'],
            ['car_make_id' => 92, 'title' => 'Roadster'],
            ['car_make_id' => 93, 'title' => 'Madison'],
            ['car_make_id' => 94, 'title' => 'CoolBear'],
            ['car_make_id' => 94, 'title' => 'Cowry'],
            ['car_make_id' => 94, 'title' => 'Cowry V80'],
            ['car_make_id' => 94, 'title' => 'Deer'],
            ['car_make_id' => 94, 'title' => 'Florid'],
            ['car_make_id' => 94, 'title' => 'Hover'],
            ['car_make_id' => 94, 'title' => 'Hover H3'],
            ['car_make_id' => 94, 'title' => 'Hover H5'],
            ['car_make_id' => 94, 'title' => 'Hover H6'],
            ['car_make_id' => 94, 'title' => 'Hover M1'],
            ['car_make_id' => 94, 'title' => 'Hover M2'],
            ['car_make_id' => 94, 'title' => 'Hover M4'],
            ['car_make_id' => 94, 'title' => 'Hover Pi'],
            ['car_make_id' => 94, 'title' => 'Pegasus'],
            ['car_make_id' => 94, 'title' => 'Peri'],
            ['car_make_id' => 94, 'title' => 'Safe'],
            ['car_make_id' => 94, 'title' => 'Sailor'],
            ['car_make_id' => 94, 'title' => 'Voleex C10 (Phenom)'],
            ['car_make_id' => 94, 'title' => 'Sing RUV'],
            ['car_make_id' => 94, 'title' => 'SoCool'],
            ['car_make_id' => 94, 'title' => 'Voleex C30'],
            ['car_make_id' => 94, 'title' => 'Wingle'],
            ['car_make_id' => 94, 'title' => 'Wingle 3'],
            ['car_make_id' => 94, 'title' => 'Wingle 5'],
            ['car_make_id' => 94, 'title' => 'Wingle 7'],
            ['car_make_id' => 95, 'title' => 'Brio'],
            ['car_make_id' => 95, 'title' => 'Princip'],
            ['car_make_id' => 95, 'title' => 'Saibao'],
            ['car_make_id' => 95, 'title' => 'Sigma'],
            ['car_make_id' => 95, 'title' => 'Simbo'],
            ['car_make_id' => 96, 'title' => '2'],
            ['car_make_id' => 96, 'title' => '3'],
            ['car_make_id' => 96, 'title' => '7'],
            ['car_make_id' => 96, 'title' => 'Family'],
            ['car_make_id' => 96, 'title' => 'Family F7'],
            ['car_make_id' => 96, 'title' => 'Freema'],
            ['car_make_id' => 96, 'title' => 'M3'],
            ['car_make_id' => 96, 'title' => 'S5'],
            ['car_make_id' => 97, 'title' => 'Rekord'],
            ['car_make_id' => 97, 'title' => 'Type 13'],
            ['car_make_id' => 98, 'title' => 'F7'],
            ['car_make_id' => 98, 'title' => 'F7x'],
            ['car_make_id' => 98, 'title' => 'H2'],
            ['car_make_id' => 98, 'title' => 'H5'],
            ['car_make_id' => 98, 'title' => 'H6'],
            ['car_make_id' => 98, 'title' => 'H6 Coupe'],
            ['car_make_id' => 98, 'title' => 'H8'],
            ['car_make_id' => 98, 'title' => 'H9'],
            ['car_make_id' => 99, 'title' => 'B21'],
            ['car_make_id' => 99, 'title' => 'Boliger'],
            ['car_make_id' => 99, 'title' => 'LaVille'],
            ['car_make_id' => 99, 'title' => 'Type 154'],
            ['car_make_id' => 100, 'title' => 'Ambassador'],
            ['car_make_id' => 100, 'title' => 'Contessa'],
            ['car_make_id' => 100, 'title' => 'Lancer'],
            ['car_make_id' => 100, 'title' => 'Pajero'],
            ]
            
        );
    }
}