<?php

namespace Database\Seeders\CarModels;

use Illuminate\Support\Facades\DB;

Class CarModelsFrom_51_to_75
{
    public static function seed()
    {
        DB::table('car_models')->insert(
           [ ['car_make_id' => 51, 'title' => '1310'],
            ['car_make_id' => 51, 'title' => '1325 Liberta'],
            ['car_make_id' => 51, 'title' => 'Docker'],
            ['car_make_id' => 51, 'title' => 'Duster'],
            ['car_make_id' => 51, 'title' => 'Logan'],
            ['car_make_id' => 51, 'title' => 'Nova'],
            ['car_make_id' => 51, 'title' => 'Pick-Up'],
            ['car_make_id' => 51, 'title' => 'Sandero'],
            ['car_make_id' => 51, 'title' => 'Solenza'],
            ['car_make_id' => 51, 'title' => 'SuperNova'],
            ['car_make_id' => 52, 'title' => 'City Leading'],
            ['car_make_id' => 52, 'title' => 'Shuttle'],
            ['car_make_id' => 53, 'title' => 'Smoothing'],
            ['car_make_id' => 54, 'title' => 'Alphion'],
            ['car_make_id' => 54, 'title' => 'Arcadia'],
            ['car_make_id' => 54, 'title' => 'Chairman'],
            ['car_make_id' => 54, 'title' => 'Damas'],
        ]);
        DB::table('car_models')->insert(
        [    ['car_make_id' => 54, 'title' => 'Espero'],
            ['car_make_id' => 54, 'title' => 'Evanda'],
            ['car_make_id' => 54, 'title' => 'G2X'],
            ['car_make_id' => 54, 'title' => 'Gentra'],
            ['car_make_id' => 54, 'title' => 'Kalos'],
            ['car_make_id' => 54, 'title' => 'Korando'],
            ['car_make_id' => 54, 'title' => 'Lacetti'],
            ['car_make_id' => 54, 'title' => 'Lacetti Premier'],
            ['car_make_id' => 54, 'title' => 'Lanos'],
            ['car_make_id' => 54, 'title' => 'Leganza'],
            ['car_make_id' => 54, 'title' => 'Lemans'],
            ['car_make_id' => 54, 'title' => 'Magnus'],
            ['car_make_id' => 54, 'title' => 'Matiz'],
            ['car_make_id' => 54, 'title' => 'Matiz Creative'],
            ['car_make_id' => 54, 'title' => 'Musso'],
            ['car_make_id' => 54, 'title' => 'Nexia'],
            ['car_make_id' => 54, 'title' => 'Nubira'],
            ['car_make_id' => 54, 'title' => 'Prince'],
            ['car_make_id' => 54, 'title' => 'Racer'],
            ['car_make_id' => 54, 'title' => 'Rezzo'],
            ['car_make_id' => 54, 'title' => 'Royale'],
            ['car_make_id' => 54, 'title' => 'Sens'],
            ['car_make_id' => 54, 'title' => 'Tacuma'],
            ['car_make_id' => 54, 'title' => 'Tico'],
            ['car_make_id' => 54, 'title' => 'Tosca'],
            ['car_make_id' => 54, 'title' => 'Winstorm'],
            ['car_make_id' => 55, 'title' => 'Altis'],
            ['car_make_id' => 55, 'title' => 'Applause'],
            ['car_make_id' => 55, 'title' => 'Atrai'],
            ['car_make_id' => 55, 'title' => 'Be-Go'],
            ['car_make_id' => 55, 'title' => 'Bee'],
            ['car_make_id' => 55, 'title' => 'Boon'],
            ['car_make_id' => 55, 'title' => 'Boon Luminas'],
            ['car_make_id' => 55, 'title' => 'Cast'],
            ['car_make_id' => 55, 'title' => 'Ceria'],
            ['car_make_id' => 55, 'title' => 'Charade'],
            ['car_make_id' => 55, 'title' => 'Chamant'],
        ]);
        DB::table('car_models')->insert(
        [    ['car_make_id' => 55, 'title' => 'Coo'],
            ['car_make_id' => 55, 'title' => 'Copen'],
            ['car_make_id' => 55, 'title' => 'Cuore'],
            ['car_make_id' => 55, 'title' => 'Delta Wagon'],
            ['car_make_id' => 55, 'title' => 'Esse'],
            ['car_make_id' => 55, 'title' => 'Extol'],
            ['car_make_id' => 55, 'title' => 'Fellow'],
            ['car_make_id' => 55, 'title' => 'Feroza'],
            ['car_make_id' => 55, 'title' => 'Gran Move'],
            ['car_make_id' => 55, 'title' => 'Hijet'],
            ['car_make_id' => 55, 'title' => 'Leeza'],
            ['car_make_id' => 55, 'title' => 'Materia'],
            ['car_make_id' => 55, 'title' => 'Max'],
            ['car_make_id' => 55, 'title' => 'Mebias'],
            ['car_make_id' => 55, 'title' => 'Midget'],
            ['car_make_id' => 55, 'title' => 'Mira'],
            ['car_make_id' => 55, 'title' => 'Mira e:S'],
            ['car_make_id' => 55, 'title' => 'Mira Gino'],
            ['car_make_id' => 55, 'title' => 'Move'],
            ['car_make_id' => 55, 'title' => 'Move Canbus'],
            ['car_make_id' => 55, 'title' => 'Move Conte'],
            ['car_make_id' => 55, 'title' => 'Naked'],
            ['car_make_id' => 55, 'title' => 'Opti'],
            ['car_make_id' => 55, 'title' => 'Rocky'],
            ['car_make_id' => 55, 'title' => 'Ruger'],
            ['car_make_id' => 55, 'title' => 'Sirion'],
            ['car_make_id' => 55, 'title' => 'Sonica'],
            ['car_make_id' => 55, 'title' => 'Storia'],
            ['car_make_id' => 55, 'title' => 'Tanto'],
            ['car_make_id' => 55, 'title' => 'Terios'],
            ['car_make_id' => 55, 'title' => 'Thor'],
            ['car_make_id' => 55, 'title' => 'Trevis'],
            ['car_make_id' => 55, 'title' => 'Wake'],
            ['car_make_id' => 55, 'title' => 'Xenia'],
            ['car_make_id' => 55, 'title' => 'YRV'],
        ]);
        DB::table('car_models')->insert(
        [    ['car_make_id' => 56, 'title' => 'SP250'],
            ['car_make_id' => 56, 'title' => 'Super 8'],
            ['car_make_id' => 56, 'title' => 'V8'],
            ['car_make_id' => 57, 'title' => 'Stradale'],
            ['car_make_id' => 58, 'title' => 'Fun'],
            ['car_make_id' => 59, 'title' => '240Z'],
            ['car_make_id' => 59, 'title' => 'Go+'],
            ['car_make_id' => 59, 'title' => 'Laurel'],
            ['car_make_id' => 59, 'title' => 'mi-Do'],
            ['car_make_id' => 59, 'title' => 'on-Do'],
            ['car_make_id' => 59, 'title' => 'Stanza'],
            ['car_make_id' => 59, 'title' => 'Urvan'],
            ['car_make_id' => 60, 'title' => 'BiGua'],
            ['car_make_id' => 61, 'title' => 'Guara'],
            ['car_make_id' => 61, 'title' => 'LongChamp'],
            ['car_make_id' => 61, 'title' => 'Magusta'],
            ['car_make_id' => 62, 'title' => 'Zephyr'],
            ['car_make_id' => 63, 'title' => 'D6'],
            ['car_make_id' => 64, 'title' => 'DMC-12'],
            ['car_make_id' => 65, 'title' => 'Antelope'],
            ['car_make_id' => 65, 'title' => 'Aurora'],
            ['car_make_id' => 63, 'title' => 'Cowboy'],
            ['car_make_id' => 63, 'title' => 'Land Crown'],
            ['car_make_id' => 63, 'title' => 'Plutus'],
            ['car_make_id' => 63, 'title' => 'Saladin'],
            ['car_make_id' => 63, 'title' => 'Shuttle'],
            ['car_make_id' => 64, 'title' => 'Custom'],
            ['car_make_id' => 64, 'title' => 'Firedome'],
            ['car_make_id' => 64, 'title' => 'Fireflite'],
            ['car_make_id' => 65, 'title' => 'V-21'],
            ['car_make_id' => 66, 'title' => '3=6'],
            ['car_make_id' => 67, 'title' => '600'],
            ['car_make_id' => 67, 'title' => 'Aries'],
            ['car_make_id' => 67, 'title' => 'Attitude'],
            ['car_make_id' => 67, 'title' => 'Avenger'],
            ['car_make_id' => 67, 'title' => 'Caliber'],
            ['car_make_id' => 67, 'title' => 'Caravan'],
            ['car_make_id' => 67, 'title' => 'Challenger'],
        ]);
        DB::table('car_models')->insert(
        [    ['car_make_id' => 67, 'title' => 'Charger'],
            ['car_make_id' => 67, 'title' => 'Charger Daytona'],
            ['car_make_id' => 67, 'title' => 'Colt'],
            ['car_make_id' => 67, 'title' => 'Custom Royale'],
            ['car_make_id' => 67, 'title' => 'D/W Series'],
            ['car_make_id' => 67, 'title' => 'D8'],
            ['car_make_id' => 67, 'title' => 'Dakota'],
            ['car_make_id' => 67, 'title' => 'Dart'],
            ['car_make_id' => 67, 'title' => 'Daytona'],
            ['car_make_id' => 67, 'title' => 'Diplomat'],
            ['car_make_id' => 67, 'title' => 'Durango'],
            ['car_make_id' => 67, 'title' => 'Dynasty'],
            ['car_make_id' => 67, 'title' => 'Intrepid'],
            ['car_make_id' => 67, 'title' => 'Journey'],
            ['car_make_id' => 67, 'title' => 'Lancer'],
            ['car_make_id' => 67, 'title' => 'Magnum'],
            ['car_make_id' => 67, 'title' => 'Mayfair'],
            ['car_make_id' => 67, 'title' => 'Monaco'],
            ['car_make_id' => 67, 'title' => 'Neon'],
            ['car_make_id' => 67, 'title' => 'Nitro'],
            ['car_make_id' => 67, 'title' => 'Omni'],
            ['car_make_id' => 67, 'title' => 'Polara'],
            ['car_make_id' => 67, 'title' => 'Raider'],
            ['car_make_id' => 67, 'title' => 'Ram'],
            ['car_make_id' => 67, 'title' => 'RamCharger'],
            ['car_make_id' => 67, 'title' => 'Shadow'],
            ['car_make_id' => 67, 'title' => 'Stealth'],
            ['car_make_id' => 67, 'title' => 'Spirit'],
            ['car_make_id' => 67, 'title' => 'Stratus'],
            ['car_make_id' => 67, 'title' => 'Viper'],
            ['car_make_id' => 67, 'title' => 'WC Series'],
            ['car_make_id' => 68, 'title' => '370'],
            ['car_make_id' => 68, 'title' => '580'],
            ['car_make_id' => 68, 'title' => 'A30'],
            ['car_make_id' => 68, 'title' => 'A9'],
            ['car_make_id' => 68, 'title' => 'AX7'],
            ['car_make_id' => 68, 'title' => 'H30'],
            ['car_make_id' => 68, 'title' => 'H30 Cross'],
            ['car_make_id' => 68, 'title' => 'Oting'],
            ['car_make_id' => 68, 'title' => 'Rich'],
            ['car_make_id' => 68, 'title' => 'S-30'],
        ]);
        DB::table('car_models')->insert(
        [    ['car_make_id' => 69, 'title' => 'Orion'],
            ['car_make_id' => 70, 'title' => 'D8 Cosworth'],
            ['car_make_id' => 70, 'title' => 'D8 GT'],
            ['car_make_id' => 70, 'title' => 'D8 GTO'],
            ['car_make_id' => 70, 'title' => 'D8 Zetec'],
            ['car_make_id' => 71, 'title' => '3'],
            ['car_make_id' => 71, 'title' => '4'],
            ['car_make_id' => 71, 'title' => '7'],
            ['car_make_id' => 71, 'title' => '7 Crossback'],
            ['car_make_id' => 72, 'title' => 'H3'],
            ['car_make_id' => 72, 'title' => 'H5'],
            ['car_make_id' => 73, 'title' => 'Premier'],
            ['car_make_id' => 73, 'title' => 'Summit'],
            ['car_make_id' => 73, 'title' => 'Talon'],
            ['car_make_id' => 73, 'title' => 'Vision'],
            ['car_make_id' => 73, 'title' => 'Vista'],
            ['car_make_id' => 74, 'title' => 'Series IV'],
            ['car_make_id' => 74, 'title' => 'Series V'],
            ['car_make_id' => 74, 'title' => 'Series IV'],
            ['car_make_id' => 75, 'title' => '6371'],
            ['car_make_id' => 75, 'title' => 'Audi 100'],
            ['car_make_id' => 75, 'title' => 'Audi A6'],
            ['car_make_id' => 75, 'title' => 'Bestube T99'],
            ['car_make_id' => 75, 'title' => 'Bestube B30'],
            ['car_make_id' => 75, 'title' => 'Bestube B50'],
            ['car_make_id' => 75, 'title' => 'Bestube B70'],
            ['car_make_id' => 75, 'title' => 'Bestube X40'],
            ['car_make_id' => 75, 'title' => 'Bestube X80'],
            ['car_make_id' => 75, 'title' => 'D60'],
            ['car_make_id' => 75, 'title' => 'Jinn'],
            ['car_make_id' => 75, 'title' => 'Oley'],
            ['car_make_id' => 75, 'title' => 'S80'],
            ['car_make_id' => 75, 'title' => 'V2'],
            ['car_make_id' => 75, 'title' => 'V5'],
            ['car_make_id' => 75, 'title' => 'Vita'],
            ['car_make_id' => 75, 'title' => 'Volkswagen Bora'],
            ['car_make_id' => 75, 'title' => 'Volkswagen City Golf'],
            ['car_make_id' => 75, 'title' => 'Volkswagen Jetta'],
]        );
    }
}
